version: '3.8'

networks:
  kurrent-grafana-network:

services:
  prometheus:
    image: prom/prometheus:v2.45.6
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090
    networks:
      - kurrent-grafana-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:10.4.4
    volumes:
      - ./config/grafana/etc-grafana-provisioning:/etc/grafana/provisioning
      - ./data/grafana/var-lib-grafana:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - kurrent-grafana-network
 
  otel-collector:
    image: otel/opentelemetry-collector:0.103.1
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    networks:
      - kurrent-grafana-network
