global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'scrape-otel-collector'
    scrape_interval: 1s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: "scrape-kurrentdb"
    scheme: https
    static_configs:
      - targets: ["host.docker.internal:2111"]
      - targets: ["host.docker.internal:2112"]
      - targets: ["host.docker.internal:2113"]
      - targets: ["host.docker.internal:2114"]
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: admin
      password: changeit
